#pragma once

#include <string>

// dlver.h will auto generated by `update_version.py` before build
// if you cant run this script, please copy this code to src/dlver.h
/*

#pragma once

#define LATEST_UPDATE_TIMESTAMP 0
#define DOWNLOADER_VERSION 0
#define DOWNLOADER_VERSION_STR "unknown"

 */
#include "dlver.h"

namespace misc {
class VersionManager {
    inline static int s_LatestVersionCode = 0;
    inline static std::string s_LatestVersionName = "unknown";

public:
    static void CheckUpdate(bool force = false);
    static int GetLatestVersionCode() { return s_LatestVersionCode; }
    static std::string_view GetLatestVersionName() { return s_LatestVersionName; }

    static int GetCurrentVersionCode() { return DOWNLOADER_VERSION; }
    static std::string_view GetCurrentVersionName() { return DOWNLOADER_VERSION_STR; }

    static bool IsLatest() {
        return GetCurrentVersionCode() >= s_LatestVersionCode;
    }
};
}
